name: Deploy to sandbox

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Publish to sandbox
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.64.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install dependencies
        run: npm ci

      - name: Generate Compressed images
        run: npm run build:images

      - name: Generate SVG icons
        run: npm run build:icons

      - name: Generate pages CSS
        run: npm run build:styles

      - name: Build Site
        run: hugo -F

#      - name: Generate schedule in PDF
#        run: node tools/pdf.js

      - name: Generate PWA service worker
        run: npm run build:service-worker

      - name: Optimize HTML / JS / CSS
        run: npm run build:minify

      - name: Configure to Sandbox
        uses: w9jds/firebase-action@v1.2.0
        with:
          args: use default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Publish to Sandbox
        uses: w9jds/firebase-action@v1.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 08_site-applimobile
